### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Feel free to edit this as you wish before merging.
Thanks for the downgrader !

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
You destroyed all the newlines by removing the double whitespace at the end of each line.

**Comment by TheOfficialFloW** [comment]
Closed, because no response.

**Comment by CelesteBlue-dev** [comment]
So double whitespace = newline ?

**Comment by StepS-** [comment]
It is used to format line breaks inside bullet-point lists.

**Pull request closed without merging**
